/obj/Skills/Buffs/SpecialBuffs
	SpecialSlot=1
	Banish_The_ANGELS_HEAVEN
	Shatter_The_Glass_Of_Fate
	Blanket_The_World_In_Darkness
	Sing_Her_Blessed_Song
	All_Hail_The_Crownless_King
	Glory_To_The_Comeback_King